background_opacity 0.65
enable_audio_bell no
linux_display_server wayland
hide_window_decorations titlebar-only

shell /usr/bin/fish

font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.0
