general {
    disable_loading_bar = true
    hide_cursor         = true
    grace               = 0
}

background {
    monitor  =
    color    = rgba(1a1b26ff)
}

input-field {
    monitor  =
    size     = 300, 50
    outline_thickness = 2
    dots_size         = 0.33
    dots_spacing      = 0.15
    outer_color       = rgba(7aa2f7ff)
    inner_color       = rgba(24283bff)
    font_color        = rgba(c0caf5ff)
    check_color       = rgba(7aa2f7ff)
    fail_color        = rgba(f7768eff)
    fail_transition   = 300
    placeholder_text  = <i>Password</i>
    position          = 0, -20
    halign            = center
    valign            = center
}
